### ISSUE TITLE
ver2.0の予定

### ISSUE THREAD

**Issue by na-trium-144** [na-trium-144/webcface#282]
### ImageMagick

- [x] ImageMagickへの移行 #270 
  - ImageFrameとcv::Matの相互変換機能を削除、Image::mat()削除
  - ImageBaseはImageFrameのエイリアスとして残し、ImageBaseWithCVは削除
  - OpenMPが有効なMagickは使えない #283 (todo?)
- <del>CMAKE_C_COMPILER, CMAKE_C_FLAGSなどのオプションへの対応</del>
- [x] 画像変換中のエラー処理 #301 
- [ ] jpeg, pngのqualityパラメーターについてドキュメントをかく

### ビルドシステム

- [x] #361 
  - client.cc, client_test.cc, server_test.ccを複数ファイルに分割し、mingwのdebugでビルドできるようになった
  - webcface-serverにlibwebcfaceを埋め込む
- [x] <del>find_packageの利用 #248, #274 </del>
- [x] <del>#284 </del>
- [x] ライブラリのディレクトリ構造の見直し #283 
- [x] <del>CMakeListsを分割 #283 </del>
- [x] <del> #327 </del>
- [x] #332, #344
- [x] cmakeのconfig生成にmesonのcmakeモジュールを使う #368
- [x] #372 
- [x] #376 
- #377 
- #379 
- #380 
### clang-tidy, warning

- [x] clang-tidy #256 
- [x] #273 
- [x] <del>#315 </del>
- [x] Warning修正 #333, 
- [x] <del>msvcで-Wallに相当するものを追加する #333 </del>
- [x] #356 
- clang-tidy17のチェックをexamples,tests,server-mainにも適用 #361
- <del>clang-format17のチェックを追加</del>

### ci

- [x] windowsのciをwindows-2019に #281 
- [x] ubuntu22,24のテストを追加 #301 

### ABI

- [x] staticビルド #274 
- [x] visibility=hidden, mingwでdllexport #274 
- [x] オプションをheaderに書き込む (webcface_static)
- [x] windowsでlibのほうにバージョン番号をつけないようにした、mingwではdllにdebugのpostfixをつけないようにした #301 
- [x] #358 
- [x] <del>EventTargetを削除しCallbackListに統一 or</del> CallbackListも消してstd::functionを1個登録する仕様にする #311 
- [x] spdlogをwebcfaceのインタフェースから削除 #316 
- [x] #329 
- [x] macでdylibのcompatibility_versionを設定 #368 
- [x] namespaceにabi_majorバージョンを追加 #368 
- [x] #373 
  - RobotJoint, RobotLinkのメンバ変数を削除しgetter関数に変更
  - ViewComponent, Canvas2DComponent, Canvas3DComponentを読み取り専用にし、TemporalViewComponent, TemporalCanvas2DComponent, TemporalCanvas3DComponent 追加
  - TemporalComponent<> の中身を変更
  - Canvas2D, Canvas3Dのdeprecatedだったadd関数を削除
- [x] #375 
  - TextをTextとVariantに分離
  - InputRef::get()の仕様変更(参照の寿命が短くなった)
  - Text::get(), getW() の戻り値を参照にした
  - ViewComponent::bind()の戻り値をVariantに

### namespace

- [x] webcface/common/ 削除 #283
  - ValAdaptor::asDouble, asInt, asLLong関数を追加し、テンプレートのas()をdeprecatedにした
  - Dict, VectorOpt 削除
- [x] #312 #317 
- [x] ver0のエラーメッセージを削除 #368 

### utf-8

- [x] string, wstring, u8stringの変換 #264 
- [x] SharedString #279 
  - LogLineData<> のメンバーアクセスをgetter関数に変更

### recv

- [x] #237 #310 
  - <del>Client::recv(), recvUntil(), waitRecv(), autoRecv(),</del> Func::setAsync() 追加
  - Func::runCond系を削除
  - wcfWaitConnection, wcfAutoConnection, <del>wcfRecv, wcfWaitRecv, wcfAutoRecv,</del> wcfFuncSetAsync, wcfFuncSetAsyncW 追加
  - Func::setで渡した関数オブジェクトがコピーされないようにした
- [x] #357 
- [x] #367 
  - recv()をsync()に統合, autoRecv削除, waitRecv→loopRecv, 受信してもしなくてもタイムアウトまで待つようにした
    - 結局 Client::sync(), loopSyncFor(), loopSyncUntil(), loopSync() になった
    - close()がsync()の送信を待機するようにした
  - AsyncFuncResult → Promise, FuncCallHandle → CallHandle 名前変更
    - Promise::started, result をdeprecatedにした
    - Promiseに各種取得関数と待機関数を実装、名前変更など
    - PromiseとCallHandleのpimplを統一
  - Func::run と operator() をdeprecatedにした
  - Func::set,setAsyncの改良 (std::functionを減らした)
  - Func::setでfutureを受け取る機能を一旦削除
  - Func::setでCallHandleを受け取るほうの仕様変更 関数終了後に自動でrespondしないようにした
  - syncDataFirst()を生成するタイミングをsync()時・接続時のどちらかに変更 (同じデータが2重で送信されるバグを修正)
  - 未接続時reqとcallを送らない
  - Func::runAsync()時にクライアントが未接続ならcallを送信しないようになった

### c_wcf

- [x] #346 
  - まだ全部は実装してない
- [x] ViewComponentなどstructを今後の機能追加に対応した構造にする #370 

### その他API

- Transformのデフォルトコンストラクタのバグを修正 (#283)
- <del>#267 </del>
- #374 
  - View << callback のときcallbackの引数にView&が使えなくなった
  - Member::onSync, onPing に引数なしコールバック設定可能にした

### Message

- [x] #325 
- <del>libName, libVersionを複数指定可能にする</del>
- [x] serverのhostname #349, https://github.com/na-trium-144/webcface-js/pull/167
- <del>webcface-launcherをserverに統合 #371 </del>
  - LauncherCommandの操作メッセージ追加

### Tools

- [x] https://github.com/na-trium-144/webcface-tools/pull/45
- [x] <del>toolsのCMakeListsでのOpenCVの扱い</del>
- [x] https://github.com/na-trium-144/webcface-tools/pull/46
- [ ] https://github.com/na-trium-144/webcface-tools/pull/38
- <del>https://github.com/na-trium-144/webcface-tools/pull/43</del>

### WebUI

- v1.7.0
  - [x] アイコン追加 https://github.com/na-trium-144/webcface-webui/pull/236
  - [x] ServerModeの名前変更→「WebCFace Desktop」
  - [x] https://github.com/na-trium-144/webcface-webui/pull/238
- v1.8.0
  - [x] https://github.com/na-trium-144/webcface-webui/issues/189, https://github.com/na-trium-144/webcface-webui/pull/241
  - [ ] 最新のlauncherに対応 (設定画面、操作画面共に)

### リリース

- Linux
  - tar.gzアーカイブにして1つにまとめたもの(lib+webui)
  - それぞれ分離したdebパッケージ(lib, tools, webui)
- Mac
  - app(frameworkとwebui含む)
    - シンボリックリンクを展開しないようにする
    - universalバイナリにする
  - brew配布(lib, tools, webuiそれぞれ)
- Windows
  - zipで1つにまとめたもの(lib+tools+webui)
  - nsis?インストーラー

### その他

- [ ] Readmeの更新 #275, #283,
- <del>webcface-pythonの更新</del>
- [x] homebrew-webcfaceの依存関係の管理 #326 
  - 依存ライブラリをすべてsharedライブラリとしてformula化する
- <del>debパッケージの依存関係 #248 </del>
